import Footer from '@/components/footer'
import Navbar from '@/components/navbar'
import './globals.css'
import { AosInit } from '@/lib/aos'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='font-primary bg-secondary'>
        <Navbar />
        <AosInit>
          {children}
        </AosInit>
      </body>
    </html>
  )
}
